const products = [
	{
		id: 'nationalExpress',
		mode: 'train',
		name: 'High Speed Train',
		short: 'ICE',
		motis: 'HIGHSPEED_RAIL',
		default: true,
	},
	{
		id: 'national',
		mode: 'train',
		name: 'Long Distance Train',
		motis: 'LONG_DISTANCE',
		motis_alt: 'NIGHT_RAIL',
		default: true,
	},
	{
		id: 'regionalExpress',
		mode: 'train',
		name: 'Regional Express',
		motis: 'REGIONAL_FAST_RAIL',
		default: true,
	},
	{
		id: 'regional',
		mode: 'train',
		bitmasks: [8],
		name: 'Regional',
		motis: 'REGIONAL_RAIL',
		motis_alt: 'OTHER',
		default: true,
	},
	{
		id: 'suburban',
		mode: 'train',
		name: 'Suburban',
		motis: 'METRO',
		default: true,
	},
	{
		id: 'bus',
		mode: 'bus',
		name: 'Bus',
		motis: 'BUS',
		motis_alt: 'COACH',
		default: true,
	},
	{
		id: 'ferry',
		mode: 'watercraft',
		name: 'Ferry',
		motis: 'FERRY',
		default: true,
	},
	{
		id: 'subway',
		mode: 'train',
		name: 'Subway',
		motis: 'SUBWAY',
		default: true,
	},
	{
		id: 'tram',
		mode: 'train',
		name: 'Tram',
		motis: 'TRAM',
		default: true,
	},
	{
		id: 'taxi',
		mode: 'taxi',
		name: 'On Demand Taxi',
		motis: 'ODM',
		default: true,
	},
];

export {
	products,
};
